version: "3.7"
name: async-api-test

services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      movies-api:
        condition: service_started

  movies-api:
    build: movies_api
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_started
      redis:
        condition: service_started
    expose:
      - "8000"
    env_file:
      - .env.example

  redis:
    image: redis:latest
    expose:
      - "6379"
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      retries: 5

  functional-tests:
    build: tests
    env_file:
      - tests/functional/.env.example
    depends_on:
      - movies-api
