[tool.black]
line-length = 120
preview = true
include = '\.py$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.env
  | _build
  | buck-out
  | build
  | dist
  | setup.cfg
)/
'''

[tool.isort]
profile = 'black'
